project_name: 'contrastive'
experiment_name: 'all_scenes'
data_path: '../'
checkpoint_path: 'tmp'
seed: 0
pretrained: false
lr: 0.001
weight_decay: 0.0001
backbone: 'resnet18'
channel_width: 64
in_channels: 5
out_channels: 0
num_classes: 0
optimizer: 'Adam'
scheduler: 'CosineAnnealingLR'
batch_size: 256
epochs: 20
progress_bar_refresh_rate: 
early_stop: false
accelerator: 'ddp'
pretrain_path: ''
queue_size: 1024