project_name: 'contrastive'
experiment_name: 'all_scenes'
data_path: '/coc/flash5/kvr6/dev/data/csr_full_v2_25-04-2023_22-06-27'
checkpoint_path: 'checkpoints'
model_lite: True # using MovoV2Lite that does not load resnet
seed: 0
pretrained: true
lr: 0.001
weight_decay: 0.0001
backbone: 'resnet18'
channel_width: 64
in_channels: 5
out_channels: 0
num_classes: 0
optimizer: 'SGD'
scheduler: 'CosineAnnealingLR'
batch_size: 16
epochs: 200
progress_bar_refresh_rate: 20
gpus:
  - 0
early_stop: false
accelerator: 'ddp'
pretrain_path: ''
train_object_representation: false
queue_size: 256
max_edge_annotations: 1000
hidden_size: 2048
